spring.application.name=TicketSystemProject3
# ===============================
# Server
# ===============================
server.port=8077
# ===============================
# PostgreSQL Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:9091/ga_db
spring.datasource.username=postgres
spring.datasource.password=secret!
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ===============================
JWT Settings
# ===============================
jwt-secret="C6UlILsE6GJwNqwCTkkvJj9O653yJUoteWMLfYyrc3vaGrrTOrJFAUD1wEBnnposzcQl"
jwt-expiration-ms=86400000
# ========================
# Cloudinry
# ========================
cloudinary.cloud_name=dabdyl0vy
cloudinary.api_key=185642818264758
cloudinary.api_secret=j8t1t-ijKl7LLuIOe3QkrX3CCMc
# ======================
# Gmail SMTP
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testjavaemail0@gmail.com
spring.mail.password=IWGCSZDKGJIAZCCW
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.from=testjavaemail0@gmail.com